cargo-features = ["edition2021"]
[package]
edition = "2021"
name = "hal-shellcode-linuxgdb"
version = "0.1.0"

[lib]
name = "hal_shellcode_linuxgdb"

[dependencies]
anyhow = {version = "1.0", default-features = false}
compiler_builtins = {git = "https://github.com/rust-lang/compiler-builtins", features = ["mem"]}
coregdb = {path = "../../core", version = "0.1.0"}
libc = {version = "0.2.106", default-features = false}
syscalls = {version = "0.5.0", default-features = false}

sc = "0.2.5"

[dependencies.common]
default-features = false
path = "../../common"
version = "0.1.0"

[dependencies.core2]
default-features = false
version = "0.3.2"
