[package]
edition = "2021"
name = "hal-shellcode-linuxgdb"
version = "0.1.0"
resolver = "2"

[lib]
name = "hal_shellcode_linuxgdb"

[dependencies]
coregdb = {path = "../../core", version = "0.1.0"}
rustix = {version = "0.34", default-features = false}

[dependencies.common]
default-features = false
path = "../../common"
version = "0.1.0"

[dependencies.core2]
default-features = false
features = ["nightly", "alloc"]
version = "0.3.2"
