cargo-features = ["edition2021"]
[package]
edition = "2021"
name = "coregdb"
version = "0.1.0"

[lib]
name = "libcore"
path = "src/lib.rs"

[dependencies]
common = {version = "0.1.0", path = "../common"}

anyhow = {version = "1.0.44", default-features = false}
base64 = {version = "0.13.0", default-features = false, features = ["alloc"]}
byteorder = {git = "https://github.com/AsafFisher/byteorder", default-features = false}
num = {version = "0.4.0", default-features = false}
num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
serde = {version = "1.0.130", default-features = false, features = ["derive"]}
minicbor =  {version = "0.14.1", default-features = false, features = ["derive"]}

serde-json-core = "0.4.0"
static-alloc = "0.2.3"

[dependencies.core2]
default-features = false
features = ["nightly", "alloc"]
version = "0.3.2"