cargo-features = ["edition2021"]
[package]
name = "standard-linuxgdb"
version = "0.1.0"
edition = "2021"

[dependencies]
coregdb = {version = "0.1.0", path = "../../core"}
common = {version = "0.1.0", path = "../../common"}
anyhow = "1.0"
bincode = "1.3.3"
[dependencies.core2]
version = "0.3.2"
